version: "3.7"

networks:
  laravel:
  app-shared:
    driver: bridge

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx${APP_NAME}
    ports:
      - "80:80"
    volumes:
      - ./src:${APP_PATH}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      - app-shared

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin${APP_NAME}
    restart: unless-stopped
    ports:
      - '3001:80'
    environment:
      PMA_HOST: mysql
    networks:
      - laravel

  mysql:
    image: library/mysql:8
    container_name: mysql${APP_NAME}
    restart: unless-stopped
    tty: true
    command: --innodb_use_native_aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - laravel

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php${APP_NAME}
    volumes:
      - ./src:${APP_PATH}
    ports:
      - "9000:9000"
    networks:
      - laravel
      - app-shared

  composer:
    build:
      context: ./php/composer
      dockerfile: Dockerfile
    container_name: composer${APP_NAME}
    volumes:
      - ./src:${APP_PATH}
    working_dir: ${APP_PATH}
    entrypoint: ['composer']
    networks:
      - laravel

  npm:
    image: library/node
    container_name: npm${APP_NAME}
    volumes:
      - ./src:${APP_PATH}
    working_dir: ${APP_PATH}
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: artisan${APP_NAME}
    volumes:
      - ./src:${APP_PATH}
    depends_on:
      - mysql
    working_dir: ${APP_PATH}
    entrypoint: ['php','${APP_PATH}/artisan']
    networks:
      - laravel

